# Site settings
title: Ankur Arora ankursmooth 
description: ankursmooth's CV
favicon: /assets/img/avatar.png
#baseurl: https://ankursmooth.com
#url: https://ankursmooth.com
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ankur Arora
  title: B.Tech. Final year, The LNMIIT
  address: Jaipur, India
  email: ankursmooth@gmail.com
  link: http://ankursmooth.com
  weibo:
  github: ankursmooth
  linkedin: ankursmooth
  twitter: ankursmooth
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: SLK Software Services Pvt. Ltd.
      location: Banglore, India
      title: Product Engineer Intern
      started: 2016
      duration: (May 2016 - July 2016 and October 2016 - March 2017)
      description: "Explored various databases: Cassandra, Neo4j. worked on 2D and 3D visualization of data. Currently working on automation of business process with real time updates."
    - work2:
      company: EventGraphia
      location: Jaipur, India
      title: PHP Developer Intern
      started: 2015
      duration: (December 2015 - February 2016)
      description: Managed database and made REST API in PHP. (login, register, event requests, support, multiple payments per order, offers, ratings)
  projectHistory:
    - project1:
      company: "Hostel Management Project and CADAC Image Sharing Portal"
      location: LNMIIT,Jaipur
      title: Backend Developer
      started: 2015
      duration: (April 2015) & (October 2015 - November 2015)
      description: "In Hostel Management, developed backend and API to be used in android application. <br>https://github.com/ankursmooth/p05-ug-hostel-allocation/ <br>In CADAC, created the Java beans class responsible for interfacing with the database and the servlets. Also corrected the bugs in servlets classes. https://github.com/cadac-image-share/cadac "

  educationHistory:
    - education1:
      organization: The LNM Institute of Information Technology
      location: Jaipur, India
      degree: Bachelor of Technology
      major: Computer Science and Engineering, 7.90/10 CGPA
      started: 2013
      duration: (2013 - 2017(expected))
    - education2:
      organization: Oxford Senior Secondary School
      location: New Delhi, India
      degree: 73% in XII (AISSCE, CBSE)
      major: Science <br>9.8/10 CGPA in X (AISSE, CBSE)
      started: "-"
      duration: 2010-2013
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional

     
