# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ankur Arora
email: ankursmooth@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>DevJournal</h1><h3>Awesome Jekyll Theme for Developers! made by Hemang</h3>Hope you like it! I will personalize it later"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ankursmooth.github.io/ankursmooth.com/" # the base hostname & protocol for your site
twitter_username: ankursmooth
github_username:  ankursmooth

# Build settings
markdown: kramdown
